### ISSUE TITLE
Not working with v24.2

### ISSUE THREAD

**Issue by rbatistajs** [djkaty/Il2CppInspector#11]
metadata - https://drive.google.com/open?id=10G-O6V7pogWsHif3ec6DLi2rQyxiiC6W
libil2cpp - https://drive.google.com/open?id=1OeG-XrONi6KUdOxiMO4P6vrT0sbrs5A8

```
Il2CppDumper -i libil2cpp.so -m global-metadata.dat
Detected metadata version 24,2
Processed 880759 relocations
Container format: ELF64
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Symbol table(s) found with 725 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x0000000001435270
CodeRegistration struct found at 0x0000000004F15BF8 (file offset 0x04F05BF8)
MetadataRegistration struct found at 0x0000000004F16650 (file offset 0x04F06650)
Analyze IL2CPP data: 15,35 sec
Create type model: 0,58 sec
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppInspector.Reflection.Extensions.ToCSharpValue(Object value, TypeInfo type, Scope usingScope) in D:\Downloads\com.bushiroad.VGzero-24-87778011-1575378249\Il2CppInspector\Il2CppInspector\Reflection\Extensions.cs:line 103
   at Il2CppInspector.Il2CppCSharpDumper.generateType(TypeInfo type, IEnumerable`1 namespaces, String prefix) in D:\Downloads\com.bushiroad.VGzero-24-87778011-1575378249\Il2CppInspector\Il2CppDumper\Il2CppCSharpDumper.cs:line 259
   at Il2CppInspector.Il2CppCSharpDumper.writeFile(String outFile, IEnumerable`1 types, Boolean useNamespaceSyntax) in D:\Downloads\com.bushiroad.VGzero-24-87778011-1575378249\Il2CppInspector\Il2CppDumper\Il2CppCSharpDumper.cs:line 107
   at Il2CppInspector.Il2CppCSharpDumper.WriteSingleFile[TKey](String outFile, Func`2 orderBy) in D:\Downloads\com.bushiroad.VGzero-24-87778011-1575378249\Il2CppInspector\Il2CppDumper\Il2CppCSharpDumper.cs:line 48
   at Il2CppInspector.App.Run(Options options) in D:\Downloads\com.bushiroad.VGzero-24-87778011-1575378249\Il2CppInspector\Il2CppDumper\Program.cs:line 131
   at Il2CppInspector.App.<>c.<Main>b__2_0(Options options) in D:\Downloads\com.bushiroad.VGzero-24-87778011-1575378249\Il2CppInspector\Il2CppDumper\Program.cs:line 78
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.App.Main(String[] args) in D:\Downloads\com.bushiroad.VGzero-24-87778011-1575378249\Il2CppInspector\Il2CppDumper\Program.cs:line 77
Generate C# code: 10,80 sec
```

**Comment by djkaty** [comment]
Thank you for the bug report! I will check it out after I get back from the Christmas break :)

**Comment by djkaty** [comment]
Fixed in commit https://github.com/djkaty/Il2CppInspector/commit/140e31b206416212f76f33068d8597b7a8e0f51a

This was an issue where the used value of an enumeration (WrapMode) in a default field value (AdvAnimationPlayer.NoneOverrideWrapMode) was undefined in the enum. I've changed it to output a cast if the enum value is undefined.

Thanks for the report!
