### ISSUE TITLE
Unhandled exception. System.AggregateException: One or more errors occurred. (Value was either too large or too small for an Int64.)

### ISSUE THREAD

**Issue by cctgapp** [djkaty/Il2CppInspector#131]
Hi Kat,

I met this problem with the latest code I just cloned. Below is the output:
`❯ ../../il2cpp.sh UnityFramework
Il2CppInspector Command-Line Edition
Version 2020.2.1
(c) 2017-2021 Katy Coe - www.djkaty.com - www.github.com/djkaty

Using plugin: Binary file XOR decryptor
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary metadata field order deobfuscator
Using plugin: IL2CPP API Discovery
Detected metadata version 24.2
Unknown symbol type: 2c   0000000005614542   radr://5614542
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Symbol table(s) found with 7397 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x0000000000175A20
CodeRegistration struct found at 0x000000000399AE20 (file offset 0x0399AE20)
MetadataRegistration struct found at 0x0000000003AF4378 (file offset 0x03AF4378)
IL2CPP binary version 24.3
Analyze IL2CPP data: 14.76 sec
Processing image 0 - ARM64 / 64-bit
Create .NET type model: 2.56 sec
IL2CPP API discovery was successful
Selected Unity version(s) 2019.3.7 - 2019.3.15 (types: 2019.3.7 - 2019.4.9, APIs: 2019.3.0 - 2019.3.15)
Create C++ application model: 12.08 sec
Unhandled exception. System.AggregateException: One or more errors occurred. (Value was either too large or too small for an Int64.)
 ---> System.OverflowException: Value was either too large or too small for an Int64.
   at System.Convert.ThrowInt64OverflowException()
   at System.UInt64.System.IConvertible.ToInt64(IFormatProvider provider)
   at Il2CppInspector.Reflection.Extensions.ToCSharpValue(Object value, TypeInfo type, Scope usingScope)
   at Il2CppInspector.Reflection.ParameterInfo.GetParameterString(Scope usingScope, Boolean emitPointer, Boolean compileAttributes) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Reflection/ParameterInfo.cs:line 126
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Il2CppInspector.Outputs.CSharpCodeStubs.generateMethod(MethodInfo method, Scope scope, String prefix) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Outputs/CSharpCodeStubs.cs:line 677
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Il2CppInspector.Outputs.CSharpCodeStubs.generateType(TypeInfo type, IEnumerable`1 namespaces, String prefix) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Outputs/CSharpCodeStubs.cs:line 574
   at Il2CppInspector.Outputs.CSharpCodeStubs.<>c__DisplayClass30_0.<writeFile>b__4(TypeInfo type, ParallelLoopState _, Dictionary`2 dict) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Outputs/CSharpCodeStubs.cs:line 232
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Func`1 localInit, Func`4 body, Action`1 localFinally)
   at Il2CppInspector.Outputs.CSharpCodeStubs.writeFile(String outFile, IEnumerable`1 types, Boolean useNamespaceSyntax, Boolean outputAssemblyAttributes) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Outputs/CSharpCodeStubs.cs:line 237
   at Il2CppInspector.Outputs.CSharpCodeStubs.WriteSingleFile[TKey](String outFile, Func`2 orderBy) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Outputs/CSharpCodeStubs.cs:line 60
   at Il2CppInspector.CLI.App.Run(Options options) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.CLI/Program.cs:line 456
   at Il2CppInspector.CLI.App.<>c.<Main>b__7_1(Options options) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.CLI/Program.cs:line 154
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Il2CppInspector.CLI.App.Main(String[] args) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.CLI/Program.cs:line 154
../../il2cpp.sh: line 2: 40425 Abort trap: 6           /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.CLI/bin/Release/netcoreapp3.1/osx-x64/Il2CppInspector -i $1
`

Here is the file. [Download](https://www.dropbox.com/s/sxkwh7c8c1vl7d7/data.zip?dl=0)
Thanks for your help.

**Comment by djkaty** [comment]
Hey again! This issue should be fixed in the latest commit. Thanks for continually posting useful issues so I can stamp out more bugs, it is appreciated :)

**Comment by cctgapp** [comment]
> Hey again! This issue should be fixed in the latest commit. Thanks for continually posting useful issues so I can stamp out more bugs, it is appreciated :)

Confirmed.
Thank you so much !!
