### ISSUE TITLE
not working version 22

### ISSUE THREAD

**Issue by warleyc** [djkaty/Il2CppInspector#14]
Hi,
 
I was trying to analyse the file below on a windows VM ( I have a mac).
The files come from a android apk :

global-metadata.dat  https://drive.google.com/open?id=1gN_Mac3UfjJ46Ip0Rjkwb-gx3GMTa2ml
libil2cpp  https://drive.google.com/open?id=1wjKmzJWdm425CXB6j1ln8w7oUkqJfCQ2

Detected metadata version 22
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppInspector.ElfReader`5.MapVATR(UInt64 uiAddr)
   at Il2CppInspector.ElfReader`5.Init()
   at Il2CppInspector.FileFormatReader`1.Load(Stream stream)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Il2CppInspector.FileFormatReader.Load(Stream stream)
   at Il2CppInspector.Il2CppInspector.LoadFromFile(String codeFile, String metadataFile)
   at Il2CppInspector.App.Run(Options options)
   at Il2CppInspector.App.<>c.<Main>b__2_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.App.Main(String[] args)

**Comment by djkaty** [comment]
Thank you for the bug report and files which I have now downloaded.

I've just returned from Christmas break so I'll look at this when I'm caught up :)

**Comment by djkaty** [comment]
There is something not right about the libil2cpp.so file. Looking at it in IDA, 2/3rds of it is empty (all zeroes) and the init_array function list mostly points to zeroed areas. The first function modifies the symbol table. There are also relocations that modify the function list. Therefore I suspect this file is obfuscated or incomplete in some way, rather than a bug in Il2CppInspector.

Il2CppInspector should not have crashed processing the relocations and I have fixed that in https://github.com/djkaty/Il2CppInspector/commit/a3fd260afc1cb7609eadf38ff0e4955e7e25ac87 .

If you have more information or if I'm mistaken about the binary file, feel free to re-open the issue 🙂
