### ISSUE TITLE
EndOfStreamException on dumping

### ISSUE THREAD

**Issue by AntyMew** [djkaty/Il2CppInspector#15]
OS: Debian 11 'bullseye'
Kernel: Linux 5.4.0 amd64

I *think* I'm using this tool correctly, but just to be sure, I'll explain my process:

* I obtained the executable and asset data of a Nintendo Switch game built using Unity
* global-metadata.dat was easy enough to find, but the executable data is made up of several ELF files, with no trace of any `libil2cpp.so` or such. I assume it's statically linked
* I tried running the CLI tool with the largest ELF passed to `-i` and the metadata file passed to `-m`. No dice, resulting in the error below
* I ran the same command with each other ELF file, with similar results

```
Detected metadata version 24.1
Processed 459528 relocations
Container format: ELF64
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0xFFFFFFFFFFFFF878
Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at NoisyCowStudios.Bin2Object.BinaryObjectReader.ReadNullTerminatedString(Encoding encoding) in /home/callie/.local/src/Il2CppInspector/Bin2Object/Bin2Object/Bin2Object.cs:line 277
   at NoisyCowStudios.Bin2Object.BinaryObjectReader.ReadNullTerminatedString(Int64 addr, Encoding encoding) in /home/callie/.local/src/Il2CppInspector/Bin2Object/Bin2Object/Bin2Object.cs:line 270
   at Il2CppInspector.ElfReader`5.GetSymbolTable() in /home/callie/.local/src/Il2CppInspector/Il2CppInspector/FileFormatReaders/ElfReader.cs:line 280
   at Il2CppInspector.Il2CppBinary.Initialize(Double version, UInt32 imageIndex) in /home/callie/.local/src/Il2CppInspector/Il2CppInspector/Il2CppBinary.cs:line 84
   at Il2CppInspector.Il2CppBinary.Load(IFileFormatReader stream, Double metadataVersion) in /home/callie/.local/src/Il2CppInspector/Il2CppInspector/Il2CppBinary.cs:line 72
   at Il2CppInspector.Il2CppInspector.LoadFromFile(String codeFile, String metadataFile) in /home/callie/.local/src/Il2CppInspector/Il2CppInspector/Il2CppInspector.cs:line 258
   at Il2CppInspector.App.Run(Options options) in /home/callie/.local/src/Il2CppInspector/Il2CppDumper/Program.cs:line 99
   at Il2CppInspector.App.<>c.<Main>b__2_0(Options options) in /home/callie/.local/src/Il2CppInspector/Il2CppDumper/Program.cs:line 78
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.App.Main(String[] args) in /home/callie/.local/src/Il2CppInspector/Il2CppDumper/Program.cs:line 77
```

Can provide executables and metadata on request, tho I'd rather put them up only temporarily, considering I'm not sure how legal it is for me to redistribute them.

**Comment by djkaty** [comment]
Sounds like you used the tool correctly. The global offset is non-sensical so I guess we are parsing the ELF file incorrectly here, or it's not an ELF file.

I'm going to be honest, I don't know anything whatsoever about Nintendo Switch games, but I'd be delighted to take a look and see if I can add support. Upload whichever files you feel comfortable with (obviously I'll need at least global-metadata.dat and one binary file - the iOS apps are statically linked as you mentioned so yours probably is too), and I'll see if I can make any sense of them!

**Comment by AntyMew** [comment]
Ahh, I see. To be more precise about the ELFs, they were actually converted from a proprietary format using a 3rd party tool; the Switch itself uses a file format very similar to ELF, called [NSO](https://switchbrew.org/w/index.php?title=NSO). Using the generated ELFs with readelf and objdump, the output seems sane, so I don't *think* they are non-compliant. But it could easily be non-standard.

Uploaded execs and metadata [here](https://drive.google.com/open?id=1_j0h-CAYz_sLG37wJttyKzaujvsaZzKn). Ty for your time!

**Comment by djkaty** [comment]
Alright, well that was a lot of work in IDA :) First up, there was seemingly a bug in the code that reads symbol tables (specifically the starting offset for a particular kind of dynamic symbol table). I ran the change through my entire 52-binary test suite with no failures, so whether that was a bug that had no adverse effect before or the offset in all the other files is zero I'm not sure, but it's fixed now. Update your clone.

Notably, IDA says that the SHT (section header table) is corrupt when it loads main.elf, so I guess it's not entirely ELF-compliant, however that problem is irrelevant to our issue here.

Now for the bad news. That wasn't enough to find the IL2CPP data. I have come up with a fix but it breaks some of the other tests so I need to look into it further to figure out exactly what's going on.

In the meantime, if you change line 146 of `Il2CppBinaryARM64.cs` as follows:

```
            var func = getFunctionAtFileOffset(image, image.MapVATR(loc), 7);
```

it will work for your particular file (use `main.elf`).

I'll make a further commit when I have a fix that works without breaking anything. If you could let me know if the output looks sane that would be great!

**Comment by AntyMew** [comment]
Seems sane to me! Constants check out, as do method pointers.

I have no idea what kind of black magic you use to make this stuff work, but it works like a charm. Thank you for the great program!

**Comment by djkaty** [comment]
Awesome, great to hear!

Hehe, well it's a combination of reading the il2cpp source code produced by Unity projects, decompiling their il2cpp.exe .NET app, and poring over all the data and pointers in IDA Pro to understand how everything works and running my code in a debugger for hours on end in Visual Studio. I have a test suite of all the previous files people have sent me plus some I created in Unity to help avoid regressions, and have wasted my life learning far more about ELF, PE, MachO file formats, ARM/x86 assembly opcodes and how IL2CPP works than I ever wanted or needed to know 😂

I'll leave this issue open until I have a commit that resolves the primary issue. Thanks for the report!

**Comment by djkaty** [comment]
Fixed in https://github.com/djkaty/Il2CppInspector/commit/ab15730e8eebc7619881d91081b79ced39a0edc4
