### ISSUE TITLE
Assembly/image index mismatch

### ISSUE THREAD

**Issue by cctgapp** [djkaty/Il2CppInspector#163]
1. Using latest Il2CppInspector.
2. CLI output: 
`cc@MacMini 2.24.2 % ../../il2cpp.sh battleroyale
Il2CppInspector Command-Line Edition
Version 2020.2
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24.1
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000100000000
Unknown symbol type: 2c   0000000005614542   radr://5614542
Symbol table(s) found with 188 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x00000001001899C4
CodeRegistration struct found at 0x00000001047692E8 (file offset 0x047692E8)
MetadataRegistration struct found at 0x0000000104864CD8 (file offset 0x04864CD8)
IL2CPP binary version 24.1
Analyze IL2CPP data: 3.02 sec
Processing image 0 - ARM64 / 64-bit
Unhandled exception. System.InvalidOperationException: Assembly/image index mismatch
   at Il2CppInspector.Reflection.Assembly..ctor(TypeModel model, Int32 imageIndex) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Reflection/Assembly.cs:line 33
   at Il2CppInspector.Reflection.TypeModel..ctor(Il2CppInspector package) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.Common/Reflection/TypeModel.cs:line 82
   at Il2CppInspector.CLI.App.Run(Options options) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.CLI/Program.cs:line 212
   at Il2CppInspector.CLI.App.<>c.<Main>b__2_0(Options options) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.CLI/Program.cs:line 115
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.CLI.App.Main(String[] args) in /Users/cheng-chungtseng/Developer/Tools/Il2CppInspector/Il2CppInspector.CLI/Program.cs:line 114
../../il2cpp.sh: line 4: 17523 Abort trap: 6           /Volumes/SSD/Developer/Tools/Il2CppInspector.2020/Il2CppInspector.CLI/bin/Release/netcoreapp3.0/osx-x64/Il2CppInspector -i $1`

3. Files:
[data](https://www.dropbox.com/s/htullypijxwi4zm/data.zip?dl=0)

**Comment by efsfssf** [comment]
Also faced with this
