### ISSUE TITLE
XOR decryptor encountered an error while executing PostProcessMetadata: Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by cctgapp** [djkaty/Il2CppInspector#164]
1. Using latest submit.
2. CLI output:
`../../../il2cpp.sh codm
Il2CppInspector Command-Line Edition
Version 2021.1
(c) 2017-2021 Katy Coe - www.djkaty.com - www.github.com/djkaty

Using plugin: Binary file XOR decryptor
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary metadata field order deobfuscator
Using plugin: IL2CPP API Discovery
Plugin Metadata strings XOR decryptor: Decrypting strings
The plugin Metadata strings XOR decryptor encountered an error while executing PostProcessMetadata: Unable to read beyond the end of the stream.. Plugin has been disabled.
Detected metadata version 23
Unknown symbol type: 2c   0000000005614542   radr://5614542
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000100000000
Symbol table(s) found with 6172 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x00000001050B7504
CodeRegistration struct found at 0x0000000108819D48 (file offset 0x08819D48)
MetadataRegistration struct found at 0x00000001089DAD08 (file offset 0x089DAD08)
The detected Il2CppCodeRegistration / Il2CppMetadataRegistration structs do not pass validation. This may mean that their fields have been re-ordered as a form of obfuscation and Il2CppInspector has not been able to restore the original order automatically. Consider re-ordering the fields in Il2CppBinaryClasses.cs and try again.
Analyze IL2CPP data: 15.32 sec`
3. [data](https://www.dropbox.com/s/fhire8tvis3vakr/data1.zip?dl=0)
4. I know this is not your issue, but if you can give me some hint on how to solve it myself is much appreciated. Thanks.

**Comment by CamelCaseName** [comment]
I get the same XOR Error, but an additional Exception:
```
Il2CppInspector Command-Line Edition
Version 2021.1
(c) 2017-2021 Katy Coe - www.djkaty.com - www.github.com/djkaty

Using plugin: IL2CPP API Discovery
Using plugin: Binary metadata field order deobfuscator
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary file XOR decryptor
Plugin Metadata strings XOR decryptor: Decrypting strings
The plugin Metadata strings XOR decryptor encountered an error while executing PostProcessMetadata: Unable to read beyond the end of the stream.. Plugin has been disabled.
Detected metadata version 24,1
Container format: PE32+
Container endianness: Little
Architecture word size: 64-bit
Instruction set: x64
Global offset: 0x0000000180000C00
No symbol table present in binary file
Required structures acquired from code heuristics. Initialization function: 0x00000001800019B0
CodeRegistration struct found at 0x0000000181EBDEA0 (file offset 0x01EBBEA0)
MetadataRegistration struct found at 0x0000000181EBE630 (file offset 0x01EBC630)
IL2CPP binary version 24,1
Analyze IL2CPP data: 1,48 sec
Processing image 0 - x64 / 64-bit
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '29' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Il2CppInspector.Reflection.Assembly..ctor(TypeModel model, Int32 imageIndex)
   at Il2CppInspector.Reflection.TypeModel..ctor(Il2CppInspector package)
   at Il2CppInspector.CLI.App.Run(Options options)
   at Il2CppInspector.CLI.App.<>c.<Main>b__7_1(Options options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Il2CppInspector.CLI.App.Main(String[] args)
```
I used the latest release and only specified the version (2018.4.35f1) I got from an asset file, the metadata and il2cpp data
[data used](https://github.com/djkaty/Il2CppInspector/files/6837004/game.zip)

If I disable the XOR plugin I get a Assembly/Index Image mismatch, but I don't know how to do this in the cli to get an error message 🤷
