### ISSUE TITLE
Attempts to create files with invalid characters when class output level is selected

### ISSUE THREAD

**Issue by Ness199X** [djkaty/Il2CppInspector#17]
```Unhandled exception. System.AggregateException: One or more errors occurred. (The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs') (The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs') (The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs') (The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs')
 ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Il2CppInspector.Outputs.CSharpCodeStubs.writeFile(String outFile, IEnumerable`1 types, Boolean useNamespaceSyntax, Boolean outputAssemblyAttributes)
   at Il2CppInspector.Outputs.CSharpCodeStubs.<>c__DisplayClass24_0.<WriteFilesByClass>b__1(TypeInfo type)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Il2CppInspector.Outputs.CSharpCodeStubs.WriteFilesByClass(String outPath, Boolean flattenHierarchy)
   at Il2CppInspector.CLI.App.Run(Options options)
   at Il2CppInspector.CLI.App.<>c.<Main>b__2_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.CLI.App.Main(String[] args)
 ---> (Inner Exception #1) System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Il2CppInspector.Outputs.CSharpCodeStubs.writeFile(String outFile, IEnumerable`1 types, Boolean useNamespaceSyntax, Boolean outputAssemblyAttributes)
   at Il2CppInspector.Outputs.CSharpCodeStubs.<>c__DisplayClass24_0.<WriteFilesByClass>b__1(TypeInfo type)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Il2CppInspector.Outputs.CSharpCodeStubs.writeFile(String outFile, IEnumerable`1 types, Boolean useNamespaceSyntax, Boolean outputAssemblyAttributes)
   at Il2CppInspector.Outputs.CSharpCodeStubs.<>c__DisplayClass24_0.<WriteFilesByClass>b__1(TypeInfo type)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #3) System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'F:\Programs\Riot\WildRiftDecompiled\floom\<PrivateImplementationDetails>.cs'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Il2CppInspector.Outputs.CSharpCodeStubs.writeFile(String outFile, IEnumerable`1 types, Boolean useNamespaceSyntax, Boolean outputAssemblyAttributes)
   at Il2CppInspector.Outputs.CSharpCodeStubs.<>c__DisplayClass24_0.<WriteFilesByClass>b__1(TypeInfo type)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

```

**Comment by djkaty** [comment]
Fixed in https://github.com/djkaty/Il2CppInspector/commit/fc7e63c0aabcbd766cf2d7cd313c7af665ac3ba9
