### ISSUE TITLE
Can't work with new update of apk

### ISSUE THREAD

**Issue by anhdd143** [djkaty/Il2CppInspector#189]
Hi, this is the file i am using. Although the most recent version of Il2CppInspector can be decoded, today's updated version of the software makes Il2CppInspector inoperable. Thank you for your attention to my problem, hope to hear from you soon.
https://drive.google.com/drive/folders/1U9qYixfG3_Kz84hg2091o15qRJUKNvgK
when load metadata:
![image](https://user-images.githubusercontent.com/33306602/135232404-4e17a816-57e1-4fe9-a5b9-41306e44e146.png)
libil2cpp:
![image](https://user-images.githubusercontent.com/33306602/135232532-1d823954-cc39-4d9e-8936-fda72eb7727b.png)
Using plugin: IL2CPP API Discovery
Using plugin: Binary metadata field order deobfuscator
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary file XOR decryptor

**Comment by ShinierLion** [comment]
I think there is a problem with a new version of the metadata.



I can replicate this bug with the new version of PokeOne (win 32x).
Here is the console log:
```
>"D:\...\Il2CppInspector.CLI\bin\Release\netcoreapp3.1\win-x86\Il2CppInspector.exe" -m global-metadata.dat -i GameAssembly.dll

Il2CppInspector Command-Line Edition
Version 2021.1
(c) 2017-2021 Katy Coe - www.djkaty.com - www.github.com/djkaty

Using plugin: IL2CPP API Discovery
Using plugin: Binary metadata field order deobfuscator
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary file XOR decryptor
Plugin Metadata strings XOR decryptor: Decrypting strings
The plugin Metadata strings XOR decryptor encountered an error while executing PostProcessMetadata: Exception of type 'System.OutOfMemoryException' was thrown.. Plugin has been disabled.
Detected metadata version 24.1
Themida protection detected
Container format: PE32
Container endianness: Little
Architecture word size: 32-bit
Instruction set: x86
Global offset: 0x0000000010000C00
No symbol table present in binary file
No matches via code heuristics
No matches via data heuristics
IL2CPP binary appears to be packed - attempting to unpack and retrying
No symbol table present in binary file
No matches via code heuristics
Required structures acquired from data heuristics
CodeRegistration struct found at 0x00000000597E5000 (file offset 0x00DC5000)
MetadataRegistration struct found at 0x00000000597E5070 (file offset 0x00DC5070)
IL2CPP binary version 24.1
Analyze IL2CPP data: 3.22 sec
Processing image 0 - x86 / 32-bit
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '29' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Il2CppInspector.Reflection.Assembly..ctor(TypeModel model, Int32 imageIndex) in D:\DLL stuff\Il2CppInspector\Source\Il2CppInspector\Il2CppInspector.Common\Reflection\Assembly.cs:line 44
   at Il2CppInspector.Reflection.TypeModel..ctor(Il2CppInspector package) in D:\DLL stuff\Il2CppInspector\Source\Il2CppInspector\Il2CppInspector.Common\Reflection\TypeModel.cs:line 84
   at Il2CppInspector.CLI.App.Run(Options options) in D:\DLL stuff\Il2CppInspector\Source\Il2CppInspector\Il2CppInspector.CLI\Program.cs:line 401
   at Il2CppInspector.CLI.App.<>c.<Main>b__7_1(Options options) in D:\DLL stuff\Il2CppInspector\Source\Il2CppInspector\Il2CppInspector.CLI\Program.cs:line 154
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Il2CppInspector.CLI.App.Main(String[] args) in D:\DLL stuff\Il2CppInspector\Source\Il2CppInspector\Il2CppInspector.CLI\Program.cs:line 154
Create .NET type model: 2.79 sec
```

### Download links
[PokeOne (win 32x) launcher](https://www.pokeonecommunity.com/index.php?mod=files&action=view&id=17)
[PokeOne (android) client](https://www.pokeonecommunity.com/index.php?mod=files&action=view&id=20)
[PokeOne (win 32x) GameAssembly.dll](https://mega.nz/file/rZgiFATZ#kyZnxCNkXl3FDVaQLujDHPijG4KKiGwxW1_SKF7EsFM)
[PokeOne (win 32x) metadata](https://mega.nz/file/fdo0xIqJ#5s2g5yUoJF3bMt0aCPFRNw2vfTO-m1rH06FMEVd1cF4)
