### ISSUE TITLE
Unhandled Exception Error in il2cppinspector

### ISSUE THREAD

**Issue by Metalsans** [djkaty/Il2CppInspector#19]
Il2CppInspector Command-Line Edition
Version 2.0
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24.1
Processed 373598 relocations
Container format: ELF64
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Symbol table(s) found with 704 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x0000000000899E0C
CodeRegistration struct found at 0x0000000002A7DE08 (file offset 0x02A6DE08)
MetadataRegistration struct found at 0x0000000002A7DE78 (file offset 0x02A6DE78)
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 8790
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Il2CppInspector.Il2CppInspector..ctor(Il2CppBinary binary, Metadata metadata)
   at Il2CppInspector.Il2CppInspector.LoadFromFile(String codeFile, String metadataFile)
   at Il2CppInspector.CLI.App.Run(Options options)
   at Il2CppInspector.CLI.App.<>c.<Main>b__2_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.CLI.App.Main(String[] args)
Analyze IL2CPP data: 6.37 sec

it spits out those errors every time when i use inspector.
that file might be obfuscated 'ConfuserEx', and i think this makes errors.

[publish.zip](https://github.com/djkaty/Il2CppInspector/files/4178929/publish.zip)

**Comment by djkaty** [comment]
Hey Metalsans, thanks for your report!

You just caught me going to bed so I took a quick look at this. I can confirm it was a bug in Il2CppInspector which causes it to crash when iterating over assemblies if any assembly besides the last one has zero .NET custom attributes.

This bug is now fixed in the latest commit - there is also a new GUI available if you're a Windows later so feel free to give it a shot if you like!

Many thanks for the report!
