### ISSUE TITLE
Not working with v24

### ISSUE THREAD

**Issue by roby65** [djkaty/Il2CppInspector#4]
From the latest commit I thought that this would work with metadata v24, but there isn't a check for v24 so it says that the version is not supported. If I remove the check, it crashes after 20 seconds. Is v24 still a WIP?

> Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppInspector.Reflection.Il2CppReflector.GetType(Il2CppType pType, MemberTypes memberType) in D:\Fevgames\Il2CppInspector\Il2CppInspector\Il2CppReflector.cs:line 55
   at Il2CppInspector.Reflection.ParameterInfo.get_ParameterType() in D:\Fevgames\Il2CppInspector\Il2CppInspector\Reflection\ParameterInfo.cs:line 38
   at Il2CppInspector.Il2CppDumper.WriteFile(String outFile) in D:\Fevgames\Il2CppInspector\Il2CppDumper\Il2CppDumper.cs:line 136
   at Il2CppInspector.App.Main(String[] args) in D:\Fevgames\Il2CppInspector\Il2CppDumper\Program.cs:line 50

**Comment by djkaty** [comment]
It's not checked per se; instead it uses .NET attributes on the data structures to alter the format of the data that is read in based on the metadata version. It should work but I don't have any v24 samples, could you supply one and I'll be happy to look at it today :)

**Comment by iBotPeaches** [comment]
Thanks!

metadata - https://drive.google.com/open?id=10u7EWifa2otQ_D-VwcQsJ6dUijNwnSV9
libil2cpp - https://drive.google.com/open?id=1SbXIsq7KyxHJS0AqE8VT8xto8a_2wG2X

**Comment by djkaty** [comment]
Okay the issue wasn't actually with the metadata, it was to do with System.TypedReference. Give it a try now and let me know how it goes :)

**Comment by iBotPeaches** [comment]
All good here, working great.

Thanks for fast response & fix.

**Comment by djkaty** [comment]
You're welcome :) Closing issue.
