### ISSUE TITLE
Error when process this file.

### ISSUE THREAD

**Issue by cctgapp** [djkaty/Il2CppInspector#90]
Hi Kat,
    I met an error when processing this file, please help to take a look. I'm using the latest code. Thanks.
```
Detected metadata version 24.1
Container format: Mach-O 64-bit
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000100000000
Unknown symbol type: 2c   0000000005614542   radr://5614542
Symbol table(s) found with 53 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x00000001001E4230
CodeRegistration struct found at 0x0000000103BD8108 (file offset 0x03BD8108)
MetadataRegistration struct found at 0x0000000103C79F60 (file offset 0x03C79F60)
IL2CPP binary version 24.1
Analyze IL2CPP data: 3.52 sec
Processing image 0 - ARM64 / 64-bit
Create .NET type model: 1.83 sec
Unknown symbol type: 2c   0000000005614542   radr://5614542
No exact match for IL2CPP APIs found in binary - IL2CPP API availability in C++ project will be partial
Selected Unity version(s) 2018.4.18 - 2018.4.99 (types: 2018.4.18 - 2018.4.99, APIs: 2018.3.0 - 2018.4.99)
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Il2CppInspector.Cpp.CppType' to type 'Il2CppInspector.Cpp.CppComplexType'.
   at Il2CppInspector.Cpp.CppTypeCollection.Struct(String name, Int32 alignmentBytes)
   at Il2CppInspector.Cpp.CppDeclarationGenerator.GenerateValueFieldStruct(TypeInfo ti)
   at Il2CppInspector.Cpp.CppDeclarationGenerator.GenerateVisitedFieldStructs()
   at Il2CppInspector.Cpp.CppDeclarationGenerator.GenerateRemainingTypeDeclarations()
   at Il2CppInspector.Model.AppModel.Build(UnityVersion unityVersion, CppCompilerType compiler, Boolean silent)
   at Il2CppInspector.CLI.App.Run(Options options)
   at Il2CppInspector.CLI.App.<>c.<Main>b__2_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.CLI.App.Main(String[] args)
```

[https://www.dropbox.com/s/h3ff39emm6bfftl/normal.zip?dl=0](url)

**Comment by djkaty** [comment]
This bug is resolved in https://github.com/djkaty/Il2CppInspector/commit/9746a6f4a83002ce3a800eb5bfbf687756587226 - thank you for the bug report!

**Comment by cctgapp** [comment]
Great.
Thanks!
