### ISSUE TITLE
Bytecode stripper step fails in IL2CppTests

### ISSUE THREAD

**Issue by AxelHu** [djkaty/Il2CppInspector#92]
Hi katy.
I'm trying to go forward from C#->IL->cpp, bing search brought me to you blog and your blog brought me here.

I tried the il2cpp.ps1( it's renamed? ) script in IL2CppTests, it failed on the bytecode stripper step, any idea why?

The unity version I uses is 2019.4.2f1, and I pass the absolute path in as parameter.

Here is the log:
```
Universal IL2CPP Build Utility
(c) 2019-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Could not find Android NDK at 'D:\Unity\2019.4.0f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK'
Using C# compiler at 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe'
Using Unity installation at 'D:\Unity\2019.4.0f1\Editor\Data'
Using IL2CPP toolchain at 'D:\Unity\2019.4.0f1\Editor\Data\il2cpp\build\deploy\net471\il2cpp.exe'
Using Unity mscorlib assembly at 'D:\Unity\2019.4.0f1\Editor\Data\MonoBleedingEdge\lib\mono\unityaot\mscorlib.dll'
Android build is disabled due to missing components
Targeted Unity version: 2019.4.0.717686

Compiling source code...
ArraysAndPointers.cs -> ArraysAndPointers.dll
CSharp1.cs -> CSharp1.dll
CSharp2.cs -> CSharp2.dll
CSharp3.cs -> CSharp3.dll
CustomAttributeData.cs -> CustomAttributeData.dll
Enums.cs -> Enums.dll
ExplicitInterfaces.cs -> ExplicitInterfaces.dll
GenericTypes.cs -> GenericTypes.dll
Methods.cs -> Methods.dll
PartialGenericTypes.cs -> PartialGenericTypes.dll
Properties.cs -> Properties.dll
References.cs -> References.dll
Scope.cs -> Scope.dll
VTablesAndLayout.cs -> VTablesAndLayout.dll
Running bytecode stripper on ArraysAndPointers.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on CSharp1.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on CSharp2.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on CSharp3.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on CustomAttributeData.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on Enums.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on ExplicitInterfaces.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on GenericTypes.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on Methods.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on PartialGenericTypes.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on Properties.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on References.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on Scope.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running bytecode stripper on VTablesAndLayout.dll...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly ArraysAndPointers.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly CSharp1.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly CSharp2.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly CSharp3.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly CustomAttributeData.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly Enums.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly ExplicitInterfaces.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly GenericTypes.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly Methods.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly PartialGenericTypes.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly Properties.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly References.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly Scope.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Converting assembly VTablesAndLayout.dll to C++...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Running il2cpp compiler for GameAssembly-ArraysAndPointers-x86 (WindowsDesktop/x86)...


   由于 Exception.ToString() 失败，因此无法打印异常字符串。
Write-Error: D:\git\gitStash\temp\Il2CppInspector-master\Il2CppTests\il2cpp.ps1:289:2
Line |
 289 |      Do-IL2CPP-Build WindowsDesktop x86 $_.BaseName $baselibX86Arg
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | IL2CPP error - aborting
```

The chinese string means " due to Exception.ToString() failure, can't print exception string"

**Comment by djkaty** [comment]
Okay... I guess the reason Exception.ToString() doesn't print the exception string is because it too is in Chinese? Therefore I can't actually see what the error is. Could you try switching your language to English temporarily to see what error is produced? If it works with English locale, there may be a bug in Unity's bytecode stripper itself.

**Comment by AxelHu** [comment]
I figure it out, `>$null` redirects all output so no error message is printed. And the real problem is that my powershell seems to process the `,` seperated arguments incorrectly.

This is the powershell version I use
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by djkaty** [comment]
I've been developing on Powershell 5.1 which is the version that ships with Windows 10 for the last few years.

I installed the latest Powershell 7 x64 preview on Windows to test and indeed see this error in the bytecode stripper section:

```
Running bytecode stripper on ArraysAndPointers.dll...

Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Unity.Options.OptionsParser.<>c__DisplayClass35_0.<ActionFor>b__5(String v)
   at NDesk.Options.Option.Invoke(OptionContext c)
   at NDesk.Options.OptionSet.Parse(String argument, OptionContext context)
   at NDesk.Options.OptionSet.Parse(IEnumerable`1 arguments, String currentDirectory)
   at Unity.Options.OptionsParser.Prepare(String[] commandLine, Type[] types, Func`3 customValueParser, String currentDirectory, Object[] instances)
   at Unity.Linker.LinkerOptions.InitAndSetup(String[] args)
   at Unity.Linker.UnityDriver..ctor(String[] args)
   at Unity.Linker.Program.Main(String[] args)
Running bytecode stripper on CSharp1.dll...

Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Unity.Options.OptionsParser.<>c__DisplayClass35_0.<ActionFor>b__5(String v)
   at NDesk.Options.Option.Invoke(OptionContext c)
   at NDesk.Options.OptionSet.Parse(String argument, OptionContext context)
   at NDesk.Options.OptionSet.Parse(IEnumerable`1 arguments, String currentDirectory)
   at Unity.Options.OptionsParser.Prepare(String[] commandLine, Type[] types, Func`3 customValueParser, String currentDirectory, Object[] instances)
   at Unity.Linker.LinkerOptions.InitAndSetup(String[] args)
   at Unity.Linker.UnityDriver..ctor(String[] args)
   at Unity.Linker.Program.Main(String[] args)
```

The errors are not suppressed (there is no `>$null` in this part of the code, and even if there was, it only suppresses stdout, not stderr).

This seems like a bug in list handling in Powershell 7. I'm not a Powershell expert and don't remember exactly how list concatenation works - do the arguments specified in `$stripperAdditionalArguments` get passed correctly with your above fix?

**Comment by AxelHu** [comment]
I don't know how to deal with the list concatenation too, I just fill all args in a single line.

Anyway, it's enough for my case, I need the cpp stuff generated by IL2CPP to do some benchmark(if possible), and I don't want to perform a full Unity build to do this. Our team is using an IL interpreter for iOS hotfix, I need some data to decide which part should go into the hotfix dll. And if it's too difficult to do in cpp, we can still go back to csharp to do the benchmark, though it's not so accurate.

**Comment by djkaty** [comment]
Alright. I'm going to leave this open and mess around in Powershell 7 when I get a chance as I think it would be a good idea to make it compatible. Thanks for bringing it to my attention!

**Comment by djkaty** [comment]
This issue is now resolved in https://github.com/djkaty/Il2CppInspector/commit/3a6b690c880297b24cffb9f0b43d5ecc94c2ea48 and the script should be compatible with PowerShell 7 (tested with 7.1.0 release version)!
